# This file enables the Travis continuous integration system, which
# automatically builds and tests the project for each GitHub commit or
# pull request on three separate JDKs.
#
# For more information, see https://travis-ci.org

sudo: true

language: scala

jdk:
  - oraclejdk8

scala:
  - 2.10.6
  - 2.11.8
  - 2.12.0

before_install:
  - export PATH=${PATH}:./vendor/bundle

env:
  - TRAVIS_NODE_VERSION="5.12.0"
  - TRAVIS_NODE_VERSION="6.10.0"
  - TRAVIS_NODE_VERSION="7.6.0"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install
  - rvm use 2.2.3 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.m2
    - $HOME/.coursier
    - $HOME/.sbt/boot

script:
  - sudo chmod +x /usr/local/bin/sbt
  - sbt ++$TRAVIS_SCALA_VERSION clean scalajavatimeJVM/test scalajavatimeJS/test scalajavatimeJVM/publishLocal scalajavatimeJS/publishLocal docs/makeMicrosite
  # Tricks to avoid unnecessary cache updates, from
  # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
